# Generated by Django 2.0.3 on 2018-03-10 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buy_price', models.PositiveIntegerField(default=1)),
                ('sell_price', models.PositiveIntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField()),
                ('buy_date', models.DateTimeField(blank=True, null=True)),
                ('listed_date', models.DateTimeField(blank=True, null=True)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Flips',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('members', models.BooleanField()),
                ('store_price', models.IntegerField(blank=True, null=True)),
                ('buy_limit', models.IntegerField(blank=True, null=True)),
                ('high_alch', models.IntegerField(blank=True, null=True)),
                ('low_alch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MissingItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buy_price', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('average_price', models.IntegerField(blank=True, null=True)),
                ('buy_volume', models.IntegerField(blank=True, null=True)),
                ('sell_volume', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Price Logs',
            },
        ),
        migrations.CreateModel(
            name='RequiredRunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Required Runes',
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('level', models.PositiveIntegerField()),
                ('xp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='merchapi.Item')),
            ],
            bases=('merchapi.item',),
        ),
        migrations.AddField(
            model_name='requiredrunes',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Spell'),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Item'),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='favorites',
            field=models.ManyToManyField(through='merchapi.Favorite', to='merchapi.Item'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='favorites',
            field=models.ManyToManyField(through='merchapi.Favorite', to='merchapi.Merchant'),
        ),
        migrations.AddField(
            model_name='flip',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Item'),
        ),
        migrations.AddField(
            model_name='flip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Item'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
        migrations.AddField(
            model_name='spell',
            name='runes',
            field=models.ManyToManyField(through='merchapi.RequiredRunes', to='merchapi.Rune'),
        ),
        migrations.AddField(
            model_name='requiredrunes',
            name='rune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Rune'),
        ),
        migrations.AlterUniqueTogether(
            name='requiredrunes',
            unique_together={('spell', 'rune')},
        ),
    ]
