# Generated by Django 2.0.3 on 2018-03-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
