# Generated by Django 2.0.3 on 2018-04-04 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('merchapi', '0006_auto_20180403_1417'), ('merchapi', '0007_auto_20180403_1442'), ('merchapi', '0008_auto_20180403_1444'), ('merchapi', '0009_auto_20180403_1524'), ('merchapi', '0010_auto_20180404_1512'), ('merchapi', '0011_remove_spell_runes'), ('merchapi', '0012_spell_runes')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchapi', '0005_auto_20180329_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceLog',
            new_name='Price',
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Prices'},
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Item')),
            ],
            options={
                'verbose_name_plural': 'Tagged Items',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Tag'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
        migrations.AddField(
            model_name='tag',
            name='items',
            field=models.ManyToManyField(related_name='tags', through='merchapi.TaggedItem', to='merchapi.Item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'item', 'user')},
        ),
        migrations.RemoveField(
            model_name='flip',
            name='user',
        ),
        migrations.AddField(
            model_name='flip',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='spell',
            name='runes',
        ),
        migrations.AddField(
            model_name='spell',
            name='runes',
            field=models.ManyToManyField(through='merchapi.RequiredRunes', to='merchapi.Rune'),
        ),
    ]
