# Generated by Django 2.0.3 on 2018-04-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0006_auto_20180403_1417_squashed_0012_spell_runes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='merchant',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('item', 'merchant')},
        ),
    ]
