# Generated by Django 2.0.3 on 2018-04-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0006_auto_20180403_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Item')),
            ],
            options={
                'verbose_name_plural': 'Tagged Items',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchapi.Tag'),
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
        migrations.AddField(
            model_name='tag',
            name='items',
            field=models.ManyToManyField(related_name='tags', through='merchapi.TaggedItem', to='merchapi.Item'),
        ),
    ]
