# Generated by Django 2.0.3 on 2018-04-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0007_auto_20180405_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
    ]
