# Generated by Django 2.0.3 on 2018-04-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0008_auto_20180403_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'item', 'user')},
        ),
    ]
