# Generated by Django 2.0.3 on 2018-04-07 17:57

from django.db import migrations
import django.db.models.deletion
import merchapi.models.item


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0008_auto_20180407_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='user',
            field=merchapi.models.item.UniqueNullForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
        ),
    ]
