# Generated by Django 2.0.3 on 2018-04-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0009_auto_20180403_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flip',
            name='user',
        ),
        migrations.AddField(
            model_name='flip',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchapi.Merchant'),
            preserve_default=False,
        ),
    ]
