# Generated by Django 2.0.3 on 2018-04-08 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0009_auto_20180407_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
