# Generated by Django 2.0.3 on 2018-04-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0010_auto_20180404_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='runes',
        ),
    ]
