# Generated by Django 2.0.3 on 2018-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapi', '0011_remove_spell_runes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='runes',
            field=models.ManyToManyField(through='merchapi.RequiredRunes', to='merchapi.Rune'),
        ),
    ]
